### ISSUE TITLE
[Feature Request] - delete file if transfer failed

### ISSUE THREAD

**Issue by STPR** [veeso/termscp#23] opened 2021-04-12 12:24 UTC
Pure-FTPd under Ubuntu and termscp under Windows 10:
termscp write file of 0 bytes when an error occur (when the filename have some characters not allowed by windows for example)

**Comment by veeso** [comment] 2021-04-12 18:45
Not a bug.

When errors occur during file transfers files are just left in the file system and doesn't apply fo FTP only, but to file explorer activity in general.
This will be implemented in 0.5.0

Reminder for me: mind that a file transfer fails also in case the file is read-only, so you shouldn't try to remove it anyway; remove only if the write process was abrupted. An internal enum `TransferAbortReason` might be required.

**Comment by veeso** [comment] 2021-05-02 09:02
Fix merged in 0.5.0

PR: #29

**Closed by veeso** 2021-05-02 09:02 UTC
Labels: enhancement, new feature
