### ISSUE TITLE
[BUG] Could not start activity manager: Could not access file: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by tedtms** [veeso/termscp#13] opened 2021-03-30 20:25 UTC
Hey!

Thanks for the quick response on my other ticket -- yay install worked fine after you updated the checksum.

I've got it installed now, but I'm getting an error on launch... regardless of what arguments I include, I always get `Could not start activity manager: Could not access file: No such file or directory (os error 2)`

I'm running Manjaro 21, not pure Arch, but that _normally_ doesn't make a difference.

**Comment by veeso** [comment] 2021-03-30 20:44
Hi,

As a Manjaro user I'm pretty sure everythingshould work there. The error reported is kinda hard to experience, and happens when termscp was unable to find or scan the current working directory. You should try to start it from another directory, maybe there is something which is causing termscp not being able to work. If it doesn't work in any of the directories of your file system, then I'll need to check on my own what's going wrong on Manjaro and if the installation through yay is somehow involved.

I had a similiar problem on WSL, when installing through Cargo, but that's another story I think. Check if termscp is installed in /usr/bin, if it is installed under /home/USER/.bin that might be a possible issue, but I'm not sure about that; in case just try to copy the executable in /tmp/ and run it from there.

**Comment by tedtms** [comment] 2021-03-30 20:50
Things seem to be in their normal place....

![image](https://user-images.githubusercontent.com/49801453/113054804-d70cad00-9177-11eb-9e92-95b30347931e.png)

But I did as you suggested and changed directories. Turns out if I go to `~/.config/termscp` I can run it successfully from there.

**Comment by veeso** [comment] 2021-03-30 21:17
I think there's something which makes termscp to fail when scanning the directory, in your working directory.

Could you please provide me with the output of `ls - la` started from the directory which is causing termscp to fail?

**Comment by tedtms** [comment] 2021-03-30 21:27
I mean, I'd love to but that's my home directory. I'd rather not post all of its file contents in a public forum lol :)

I also just confirmed that I can run it from my root directory. It seems to be my home directory that's the issue...

**Comment by veeso** [comment] 2021-03-31 07:06
That's perfectly fine, I was more interested in the permission column tbh.

The reason it fails is because, when reading the metadata of a file, one of the following errors occour, while performing `pub fn metadata<P: AsRef<Path>>(path: P) -> Result<Metadata>`:

- The user lacks permissions to perform metadata call on path.
- path does not exist.

Because of that, I've decided to change the behaviour of when termscp scans a directory, if there is an error stating a file, the file will just be ignored and will not included in the files list.

**Comment by tedtms** [comment] 2021-03-31 12:11
Oh ok, that makes more sense. I just went through my home directory and did find some root-only documents, which I no longer needed and removed. All remaining files are owned by my user/group and have rw access permissions.

However, running termscp results in the same error. Does termscp do any logging? Is there a way to see what file it's running into the problem with?

**Comment by veeso** [comment] 2021-03-31 12:25
No, unfortunately there's no logging at the moment. I've added to my todos I must always report the file name causing the error.
I actually don't expect to see the file causing this error even in ls, because probably ls won't show it either, since it is not possilbe to stat it. Maybe there is a directory with mode `0o000`.

**Comment by tedtms** [comment] 2021-03-31 12:27
How would I go about finding a directory's mode?

**Comment by veeso** [comment] 2021-03-31 12:30
I was able to reproduce the error, but I don't know if this is the case, and is very unlikely to happen actually.
It seems the directory you're trying to run termscp from, which is your home, for some reason doesn't have the execution flag set to its mode, which prevents to stat the directory.

I know this is kinda unlikely to happen, but that's exactly what is causing the problem.
What does `ls` outputs when you try to execute `ls $(pwd)`?

**Comment by tedtms** [comment] 2021-03-31 12:34
![image](https://user-images.githubusercontent.com/49801453/113144983-dfa6c700-91fb-11eb-8d7d-3974c9df3461.png)

Looks like the directory has the execution flag.

**Comment by veeso** [comment] 2021-04-01 09:56
I've checked and there shouldn't be any problem with that on Manjaro.

Just to be sure: do you run termscp in your home directory with your user `tsadler` and without any `su <other_user> termscp`. I know it might be a dummy question, but I can't really understand what's going on.

In the worst case, wait for the 0.4.1 patch to see what the log will say and if it will fix the issue.

**Comment by tedtms** [comment] 2021-04-01 13:07
yes, I am just running it as `tsadler`. Running it as other users (for example, `root`) results in the same error if running from `tsadler`'s home directory.

**Comment by veeso** [comment] 2021-04-03 15:20
Fix merged in 0.4.1 branch.

**Closed by veeso** 2021-04-03 15:20 UTC
Labels: bug
