### ISSUE TITLE
[BUG] - Chinese file error

### ISSUE THREAD

**Issue by LittleSheep2Code** [veeso/termscp#108] opened 2022-04-07 08:42 UTC
## Description

When my computer container a filename with a Chinese text, the termscp just crashed 

## Steps to reproduce

Create a file container Chinese text, then connect to server

## Expected behaviour

TermSCP do not crash

## Environment

- OS: [MacOS]
- Architecture [x86_64]
- termscp version 0.8.1
- Protocol used SFTP

## Log

```
thread 'main' panicked at 'byte index 23 is not a char boundary; it is inside '终' (bytes 21..24) of `「汉字之趣」最终版.pptx`', src/explorer/formatter.rs:
308:37
      note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional information

No additional information

**Comment by veeso** [comment] 2022-04-07 08:45
Duplicate of #104

**Closed by veeso** 2022-04-07 08:45 UTC
Labels: bug

**Comment by veeso** [comment] 2022-04-07 09:33
PR #109
