### ISSUE TITLE
[BUG] - CANNOT CONNECT WITH SCP

### ISSUE THREAD

**Issue by MyMeepSQL** [veeso/termscp#152] opened 2023-03-06 18:57 UTC
## Description

I just install TermSCP on my Manjaro Linux distro and when a tried to connect  to my Ubuntu server using SCP, it prompt me this error:

![Screenshot_20230306_193458](https://user-images.githubusercontent.com/82945541/223200399-8a8ffcf8-f1ce-4075-ab9a-62bb45bf3b5f.png)

## Steps to reproduce

 - Use SCP to connect to my Ubuntu Server from my Manjaro machine

## Expected behaviour

 - Connect to my Ubuntu Server without this error

## Environment

- OS: Manjaro Linux
- Architecture: x86_64
- Rust version: rustc 1.67.1 (d5a82bbd2 2023-02-07) (Arch Linux rust 1:1.67.1-1)
- termscp version: 0.11.0
- Protocol used: SCP
- Remote server version and name: Ubuntu 22.04.2 LTS

**Comment by veeso** [comment] 2023-03-06 22:24
It's a known problem. Please delete from configuration the ssh config path or create `~/.ssh/config`. It will be fixed soon.

Duplicate of #150

**Comment by veeso** [comment] 2023-03-07 20:02
fixed in 0.11.1

**Closed by veeso** 2023-03-07 20:02 UTC
Labels: bug

**Comment by MyMeepSQL** [comment] 2023-03-08 16:51
thanks for the fix
