### ISSUE TITLE
[QUESTION] - TITLE

### ISSUE THREAD

**Issue by wppro85** [veeso/termscp#106] opened 2022-04-06 14:38 UTC
It can not be installed on my macbook air x86 (not m1).
"Expected to find class TermscpM1, but only found: Termscp."
```
⋊> ~ curl --proto '=https' --tlsv1.2 -sSLf "https://git.io/JBhDb" | sh


  Termscp configuration
> Platform:      macos
> Arch:          x86_64

? Install termscp 0.8.1? [y/N] y
> Installing termscp…
Running `brew update --preinstall`...
==> Tapping veeso/termscp
Cloning into '/usr/local/Homebrew/Library/Taps/veeso/homebrew-termscp'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 120 (delta 30), reused 111 (delta 27), pack-reused 0
Receiving objects: 100% (120/120), 14.14 KiB | 804.00 KiB/s, done.
Resolving deltas: 100% (30/30), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/veeso/homebrew-termscp/Formula/termscp-m1.rb
No available formula with the name "termscp-m1". Did you mean termscp?
In formula file: /usr/local/Homebrew/Library/Taps/veeso/homebrew-termscp/Formula/termscp-m1.rb
Expected to find class TermscpM1, but only found: Termscp.
Error: Cannot tap veeso/termscp: invalid syntax in tap!
```

**Comment by veeso** [comment] 2022-04-07 08:23
duplicate of #107

**Closed by veeso** 2022-04-07 08:23 UTC
Labels: duplicate, question
